title: Model NASS
description: A permanent youth deliberative body. A Care for Knowledge Initiative.
url: "https://modelnass.ng"
baseurl: ""

# Build
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Site-wide data you can reference with {{ site.register_url }} etc.
register_url: "https://docs.google.com/forms/d/e/1FAIpQLSerUIeoYRMUCbqwHpb10WnGDTcPHaQRcZwDY5bL9NM54lUycw/viewform?usp=dialog"
monapedia_url: "https://wiki.modelnass.ng"
instagram_url: "https://instagram.com/modelnassng"
twitter_url: "https://x.com/modelnassng"
linkedin_url: "https://linkedin.com/company/modelnassng"
cfk_url: "https://careforknowledge.org"
